name: Triggered by Version Bump merged

on:
  push:

    paths:
      - '!**'
      - 'version.txt'
    tags-ignore:
      - '**'

jobs:
  infos:
    name: infos
    runs-on: ubuntu-latest
    steps:
      - name: Echo infos
        run: echo '${{toJSON(github)}}'
