name: Triggered by Version Bump merged

#disable all tags and enable all brannches and only version file
on:
  push:
    branches-ignore:
      - update-rc-version
    paths:
      - version.txt


jobs:
  infos:
    name: infos
    runs-on: ubuntu-latest
    outputs:
      isVersionBump: ${{ steps.checkRelease.outputs.isVersionBump }}
    steps:
      - name: Echo infos
        run: echo '${{toJSON(github)}}'

      - name: Extract needed infos
        id: checkRelease
        run: |
          echo "${{github.event.head_commit.message}}" > temp.txt
          if [[ $(grep -oP "\[v\d+.\d+.\d+rc\d+\]" temp.txt) ||   $(grep -oP "\[v\d+.\d+.\d+\]" temp.txt) ]]; then
            echo ::set-output\ name=isVersionBump::true

  createRelease:
    name: Create Release
    needs: infos
    if: needs.infos.outputs.isVersionBump == true
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder Release
        run: echo "Create Release here"