name: Triggered by set Tag

on:
  push:


jobs:
  taginfos:
    name: Print github context infos to get Tag infos
    runs-on: ubuntu-latest
    steps:
      - name: Echo infos
        run: echo '${{toJSON(github)}}'