name: Triggered by set Tag

on:
  push:
    tags:        
      - setRC**

jobs:
  taginfos:
    name: Print github context infos to get Tag infos
    runs-on: ubuntu-latest
    steps:
      - name: Echo infos
        run: echo '${{toJSON(github)}}'
      - name: extract version 
        run: echo $(grep -oP "\d+.\d+.\d+rc\d+" <<< "${{github.ref}}")
    