name: Triggered by set Tag

on:
  push:
    tags:        
      - setRC**

jobs:
  taginfos:
    name: Print github context infos to get Tag infos
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.cache.outputs.VERSION }}
      BASE: ${{ steps.cache.outputs.BASE}}
    steps:
      - name: Echo infos
        run: echo '${{toJSON(github)}}'
      - name: extract version 
        id: cache
        run: |
          echo ::set-output\ name=VERSION::$(grep -oP "\d+.\d+.\d+rc\d+" <<< "${{github.ref}}")
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-output\ name=BASE::$branch
      - run: echo ${{ steps.cache.outputs.BASE }}

  bump_version:
    name: Bump Version Number
    needs: taginfos
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Prepare package and set version
        run: |
          echo ${{ needs.taginfos.outputs.VERSION }} > version.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Version number to match specified 
          title: Update Version number
          body: Update Version number to match specified in PR Title
          branch: update-version
          base: ${{ needs.taginfos.outputs.BASE }}
    