name: Repository Dispatch Test
on:
  repository_dispatch:
    types: [plenum-updated]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.version }}
      - run: echo "Do updates and tests here"